version: '3.9'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ../../:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ../../:/var/www/html
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: gestion_produits
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
      -  ../../database/gestion_produits-psql.sql:/docker-entrypoint-initdb.d/gestion_produits-psql.sql:ro
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
