apiVersion: v1
kind: Service
metadata:
  name: gestion-produits-app
spec:
  selector:
    app: gestion-produits-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
