version: '3.9'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ../../php/www:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../../php/www:/var/www/html
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_produits
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ../../database/gestion_produits-mysql.sql:/docker-entrypoint-initdb.d/gestion_produits-mysql.sql:ro
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
